import { Router } from 'express';
import { supabaseAdmin } from '../services/supabase.js';
import verifyToken from '../middleware/auth.js';

const router = Router();

router.use(verifyToken);

// @route   POST /api/bookings
// @desc    Create a new test booking
router.post('/', async (req, res) => {
  const {
    lab_id,
    family_member_id,
    collection_mode,
    address_id,
    slot_datetime,
    items, // Array of { id: string, isPackage: boolean }
    notes,
    promo_code
  } = req.body;

  if (!lab_id || !items || items.length === 0) {
    return res.status(400).json({ error: 'Lab and booking items are required' });
  }

  try {
    // 1. Fetch commission rate for the lab partner
    const { data: lab, error: labError } = await supabaseAdmin
      .from('lab_partners')
      .select('commission_rate')
      .eq('id', lab_id)
      .single();

    if (labError || !lab) {
      return res.status(404).json({ error: 'Lab partner not found' });
    }

    const commissionRate = lab.commission_rate || 15.00;

    // 2. Fetch prices from DB to avoid client-side price tampering
    let totalAmount = 0;
    const itemsToInsert = [];

    for (const item of items) {
      if (item.isPackage) {
        const { data: pkg, error: pkgError } = await supabaseAdmin
          .from('packages')
          .select('price')
          .eq('id', item.id)
          .single();
        if (pkgError || !pkg) throw new Error(`Package with ID ${item.id} not found`);
        
        totalAmount += parseFloat(pkg.price);
        itemsToInsert.push({
          package_id: item.id,
          test_id: null,
          price_at_booking: parseFloat(pkg.price),
        });
      } else {
        const { data: test, error: testError } = await supabaseAdmin
          .from('tests')
          .select('price')
          .eq('id', item.id)
          .single();
        if (testError || !test) throw new Error(`Test with ID ${item.id} not found`);
        
        totalAmount += parseFloat(test.price);
        itemsToInsert.push({
          package_id: null,
          test_id: item.id,
          price_at_booking: parseFloat(test.price),
        });
      }
    }

    // Apply promo code if present
    let discountAmount = 0;
    if (promo_code) {
      const { data: promo, error: promoErr } = await supabaseAdmin
        .from('promo_codes')
        .select('*')
        .eq('code', promo_code.toUpperCase())
        .eq('is_active', true)
        .maybeSingle();

      if (!promoErr && promo) {
        if (!promo.min_order_value || totalAmount >= parseFloat(promo.min_order_value)) {
          if (promo.type === 'percentage') {
            discountAmount = totalAmount * (parseFloat(promo.value) / 100);
            if (promo.max_discount && discountAmount > parseFloat(promo.max_discount)) {
              discountAmount = parseFloat(promo.max_discount);
            }
          } else if (promo.type === 'fixed') {
            discountAmount = parseFloat(promo.value);
          }
          
          discountAmount = Math.round(discountAmount);

          // Update usage count
          await supabaseAdmin
            .from('promo_codes')
            .update({ usage_count: (promo.usage_count || 0) + 1 })
            .eq('id', promo.id);
        }
      }
    }

    const finalAmount = Math.max(totalAmount - discountAmount, 0);

    // 3. Calculate splits
    const commissionDeducted = (finalAmount * (commissionRate / 100));
    const labPayout = finalAmount - commissionDeducted;

    // 4. Create the booking entry (booking_number is auto-generated by DB trigger)
    const { data: booking, error: bookingError } = await supabaseAdmin
      .from('bookings')
      .insert({
        patient_user_id: req.user.id,
        family_member_id: family_member_id || null,
        lab_id,
        collection_mode: collection_mode || 'home_collection',
        address_id: collection_mode === 'home_collection' ? address_id : null,
        slot_datetime: slot_datetime || null,
        status: 'pending_lab_acceptance',
        payment_status: 'pending',
        total_amount: finalAmount,
        platform_commission: commissionDeducted,
        lab_payout_amount: labPayout,
        notes: notes || null,
      })
      .select()
      .single();

    if (bookingError) throw bookingError;

    // 5. Create booking items
    const finalItems = itemsToInsert.map(itm => ({
      ...itm,
      booking_id: booking.id,
    }));

    const { error: itemsError } = await supabaseAdmin
      .from('booking_items')
      .insert(finalItems);

    if (itemsError) throw itemsError;

    res.status(201).json(booking);
  } catch (err) {
    console.error('Error creating booking:', err);
    res.status(500).json({ error: err.message || 'Failed to create booking' });
  }
});

// @route   GET /api/bookings/my
// @desc    Get patient's bookings
router.get('/my', async (req, res) => {
  try {
    const { data, error } = await supabaseAdmin
      .from('bookings')
      .select('*, lab_partners(name, logo_url)')
      .eq('patient_user_id', req.user.id)
      .order('created_at', { ascending: false });

    if (error) throw error;
    res.json(data);
  } catch (err) {
    console.error('Error listing user bookings:', err);
    res.status(500).json({ error: 'Failed to retrieve bookings' });
  }
});

// @route   GET /api/bookings/:id
// @desc    Get detailed single booking
router.get('/:id', async (req, res) => {
  try {
    const { data: booking, error: bookingError } = await supabaseAdmin
      .from('bookings')
      .select('*, lab_partners(*), family_members(*), addresses(*)')
      .eq('id', req.params.id)
      .single();

    if (bookingError || !booking) {
      return res.status(404).json({ error: 'Booking not found' });
    }

    // Verify ownership
    if (booking.patient_user_id !== req.user.id && req.user.role !== 'platform_admin' && req.user.role !== 'lab_staff') {
      return res.status(403).json({ error: 'Unauthorized' });
    }

    // Fetch items with test details
    const { data: items, error: itemsError } = await supabaseAdmin
      .from('booking_items')
      .select('*, tests(name, code), packages(name)')
      .eq('booking_id', booking.id);

    if (itemsError) throw itemsError;

    // Fetch reports if uploaded
    const { data: reports, error: reportsError } = await supabaseAdmin
      .from('reports')
      .select('*')
      .eq('booking_id', booking.id);

    // Fetch assigned phlebotomist details if any
    const { data: assignment } = await supabaseAdmin
      .from('phlebotomist_assignments')
      .select('*, users(name, phone)')
      .eq('booking_id', booking.id)
      .maybeSingle();

    // Fetch review details if any
    const { data: review } = await supabaseAdmin
      .from('reviews')
      .select('*')
      .eq('booking_id', booking.id)
      .maybeSingle();

    res.json({
      ...booking,
      items: items || [],
      reports: reports || [],
      phlebotomist: assignment ? assignment.users : null,
      review: review || null,
    });
  } catch (err) {
    console.error('Error fetching booking detail:', err);
    res.status(500).json({ error: 'Failed to retrieve booking details' });
  }
});

// @route   PUT /api/bookings/:id/cancel
// @desc    Cancel a booking
router.put('/:id/cancel', async (req, res) => {
  try {
    // Verify booking status first
    const { data: booking, error: fetchError } = await supabaseAdmin
      .from('bookings')
      .select('status, patient_user_id')
      .eq('id', req.params.id)
      .single();

    if (fetchError || !booking) {
      return res.status(404).json({ error: 'Booking not found' });
    }

    if (booking.patient_user_id !== req.user.id) {
      return res.status(403).json({ error: 'Unauthorized to cancel this booking' });
    }

    if (['sample_collected', 'processing', 'report_ready', 'cancelled'].includes(booking.status)) {
      return res.status(400).json({ error: `Cannot cancel booking at current status: ${booking.status}` });
    }

    const { data, error } = await supabaseAdmin
      .from('bookings')
      .update({
        status: 'cancelled',
        updated_at: new Date().toISOString(),
      })
      .eq('id', req.params.id)
      .select()
      .single();

    if (error) throw error;
    res.json(data);
  } catch (err) {
    console.error('Error cancelling booking:', err);
    res.status(500).json({ error: 'Failed to cancel booking' });
  }
});

// @route   POST /api/bookings/:id/review
// @desc    Submit user rating & review for lab and phlebotomist
router.post('/:id/review', async (req, res) => {
  const { id } = req.params;
  const { lab_rating, lab_review_text, phlebotomist_rating, phlebotomist_note } = req.body;

  if (!lab_rating) {
    return res.status(400).json({ error: 'Lab rating is required' });
  }

  try {
    const { data: booking, error: bookingErr } = await supabaseAdmin
      .from('bookings')
      .select('patient_user_id')
      .eq('id', id)
      .single();

    if (bookingErr || !booking) {
      return res.status(404).json({ error: 'Booking not found' });
    }

    if (booking.patient_user_id !== req.user.id) {
      return res.status(403).json({ error: 'Unauthorized to review this booking' });
    }

    const { data: existingReview } = await supabaseAdmin
      .from('reviews')
      .select('id')
      .eq('booking_id', id)
      .maybeSingle();

    if (existingReview) {
      return res.status(400).json({ error: 'You have already reviewed this booking' });
    }

    const { data: newReview, error: reviewErr } = await supabaseAdmin
      .from('reviews')
      .insert({
        booking_id: id,
        patient_user_id: req.user.id,
        lab_rating,
        lab_review_text,
        phlebotomist_rating,
        phlebotomist_note,
      })
      .select()
      .single();

    if (reviewErr) throw reviewErr;
    res.json(newReview);
  } catch (err) {
    console.error('Error submitting review:', err);
    res.status(500).json({ error: err.message || 'Failed to submit review' });
  }
});

// @route   POST /api/bookings/:id/share
// @desc    Generate a secure, time-limited (7-day) share token for the PDF report
router.post('/:id/share', async (req, res) => {
  const { id } = req.params;
  try {
    const { data: latestReport, error: fetchErr } = await supabaseAdmin
      .from('reports')
      .select('id, file_url')
      .eq('booking_id', id)
      .eq('is_active', true)
      .order('version', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (fetchErr || !latestReport) {
      return res.status(404).json({ error: 'No active report found to share' });
    }

    const shareToken = crypto.randomUUID ? crypto.randomUUID() : (await import('crypto')).randomUUID();
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 7); // 7-day expiry

    const { data: updatedReport, error: updateErr } = await supabaseAdmin
      .from('reports')
      .update({
        share_token: shareToken,
        share_expires_at: expiresAt.toISOString(),
      })
      .eq('id', latestReport.id)
      .select()
      .single();

    if (updateErr) throw updateErr;

    res.json({
      share_token: shareToken,
      share_expires_at: expiresAt.toISOString(),
      share_url: `/patient/share/${shareToken}`
    });
  } catch (err) {
    console.error('Error generating share link:', err);
    res.status(500).json({ error: 'Failed to generate share link' });
  }
});

export default router;
